### ISSUE TITLE
PHP-Version depending issues

### ISSUE THREAD

**Issue by mediaventa** [blueglassdigital/job-postings#54]
Depending on which PHP version is set, I get different kind of issues:

PHP 8.0 and 8.1:
When I submit an application, the spinner image doesn’t stop spinning. As an applicant, I get the impression that the form has not been sent.
When sending, an entry is created in WordPress for an application received, but no e-mail is sent to the specified recipient e-mail.

Setting PHP 7.4 the situation is reversed:
The form is sent and the applicant receives the stored text that the application has been sent.
In this case, the e-mail arrives at the recipient, but no database entry is created for the application received.

Roland

**Comment by cfoellmann** [comment]
I finally did update our staging to php 8.1.x and I did not get any errors. All functions work as expected.
Submit form including uploaded file -> send via mail to our HR department.

All of you should check these points:

- tested “WP Media” -> worked for me
“Secure location” : can not test that at the moment

**Comment by mediaventa** [comment]
Hello Christian,
Thank you for testing.

I did the same once but unfortunately with the same result as described in my first post.
I change nothing but the PHP Version.

In the list of WordPress plugins is specified: "Jobs for WordPress" Version 2.5.10.2

I tested the option "File storage" with "WP Media" and "Secure location".
- Both options work with PHP 8.1
- None of the options work with PHP 7.4 and there is no entry for an received application (as described).
Nevertheless, submitting the form and sending the mail including attachment works with PHP 7.4 which is our favourite way.

**Comment by advkarl** [comment]
Hello @cfoellmann 
we also encountered this bug and i could hotfix it by changing the usage of 
`get_post_meta` in the file `job-postings/include/class-job-notifications.php`, nearby of line 305.
According to the Wordpress API the function only returns a array when the third parameter is set to false, i couldnt verify the other usages of `get_post_meta` but in our case it fixed the issue.

Greetings

**Comment by mediaventa** [comment]
Thank you advkarl,

I tested it with PHP 8.1 and it works for me too.
In my case it was line 296. I changed the code from _true_ to _false_ here:
`$meta = get_post_meta($entry_id, $key, false);`

Roland

**Comment by cfoellmann** [comment]
I looked at the code, too.
As far as I can see the `true` should be the intended value. But I recognize that your errors get solved by the change.
I am not sure how to proceed since it works for us without a change.

**Comment by cfoellmann** [comment]
what is in the error logs at your end?
There must be an error. Some kind of wrong type array or sth

**Comment by mediaventa** [comment]
I tracked the error with PHP 8.1 and deactivated the plugin Email Encoder while testing as it throws deprecated errors in between the job posting errors.

With this configuration: $meta = get_post_meta($entry_id, $key, **true**);

Error Log:

```
[02-Mar-2023 16:52:18 UTC] PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /homepages/2/d167986650/htdocs/gzo.de/wp-content/plugins/job-postings/include/class-job-application-submit.php on line 17
[02-Mar-2023 16:52:18 UTC] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /homepages/2/d167986650/htdocs/gzo.de/wp-content/plugins/job-postings/include/class-job-notifications.php:305
Stack trace:
#0 /homepages/2/d167986650/htdocs/gzo.de/wp-content/plugins/job-postings/include/class-job-notifications.php(198): JobNotifications::getAllFields('{all_fields}', '1229', 4471)
#1 /homepages/2/d167986650/htdocs/gzo.de/wp-includes/class-wp-hook.php(308): JobNotifications::convertMergeFields('{all_fields}', '1229', 4471, true)
#2 /homepages/2/d167986650/htdocs/gzo.de/wp-includes/plugin.php(205): WP_Hook->apply_filters('{all_fields}', Array)
#3 /homepages/2/d167986650/htdocs/gzo.de/wp-content/plugins/job-postings/include/class-job-notifications.php(32): apply_filters('job-postings/em...', '{all_fields}', '1229', 4471, true)
#4 /homepages/2/d167986650/htdocs/gzo.de/wp-content/plugins/job-postings/include/class-job-application-submit.php(513): JobNotifications::sendEntryEmail('1229', 4471)
#5 /homepages/2/d167986650/htdocs/gzo.de/wp-includes/class-wp-hook.php(308): JobApplicationSubmit::ajax_submit('')
#6 /homepages/2/d167986650/htdocs/gzo.de/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#7 /homepages/2/d167986650/htdocs/gzo.de/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8 /homepages/2/d167986650/htdocs/gzo.de/wp-admin/admin-ajax.php(188): do_action('wp_ajax_jobslis...')
#9 {main}
  thrown in /homepages/2/d167986650/htdocs/gzo.de/wp-content/plugins/job-postings/include/class-job-notifications.php on line 305
```


With the configuration: $meta = get_post_meta($entry_id, $key, **false**);

Error Log:

```
[02-Mar-2023 16:55:05 UTC] PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /homepages/2/d167986650/htdocs/gzo.de/wp-content/plugins/job-postings/include/class-job-application-submit.php on line 17
[02-Mar-2023 16:55:05 UTC] PHP Warning:  Undefined array key "label" in /homepages/2/d167986650/htdocs/gzo.de/wp-content/plugins/job-postings/include/class-job-notifications.php on line 305
[02-Mar-2023 16:55:05 UTC] PHP Warning:  Undefined array key "value" in /homepages/2/d167986650/htdocs/gzo.de/wp-content/plugins/job-postings/include/class-job-notifications.php on line 306
[02-Mar-2023 16:55:05 UTC] PHP Warning:  Undefined array key "label" in /homepages/2/d167986650/htdocs/gzo.de/wp-content/plugins/job-postings/include/class-job-notifications.php on line 305
[02-Mar-2023 16:55:05 UTC] PHP Warning:  Undefined array key "value" in /homepages/2/d167986650/htdocs/gzo.de/wp-content/plugins/job-postings/include/class-job-notifications.php on line 306
[02-Mar-2023 16:55:05 UTC] PHP Warning:  Undefined array key "label" in /homepages/2/d167986650/htdocs/gzo.de/wp-content/plugins/job-postings/include/class-job-notifications.php on line 305
[02-Mar-2023 16:55:05 UTC] PHP Warning:  Undefined array key "value" in /homepages/2/d167986650/htdocs/gzo.de/wp-content/plugins/job-postings/include/class-job-notifications.php on line 306
[02-Mar-2023 16:55:05 UTC] PHP Notice:  unserialize(): Error at offset 0 of 13 bytes in /homepages/2/d167986650/htdocs/gzo.de/wp-content/plugins/job-postings/include/class-job-notifications.php on line 55
[02-Mar-2023 16:55:05 UTC] PHP Notice:  unserialize(): Error at offset 0 of 24 bytes in /homepages/2/d167986650/htdocs/gzo.de/wp-content/plugins/job-postings/include/class-job-notifications.php on line 55
[02-Mar-2023 16:55:05 UTC] PHP Notice:  unserialize(): Error at offset 0 of 11 bytes in /homepages/2/d167986650/htdocs/gzo.de/wp-content/plugins/job-postings/include/class-job-notifications.php on line 55
```

**Comment by infazz** [comment]
@mediaventa please try the lates version, hopefully it fixes your issue :)

**Comment by mediaventa** [comment]
Thank you for the upgrade to version 2.5.11.1.
I tested it and it works with PHP 8.1 without errors.
